apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-scheduling-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-scheduling
  template:
    metadata:
      labels:
        app: appointment-scheduling
    spec:
      containers:
      - name: appointment-scheduling-container
        image: your-docker-repo/appointment-scheduling-service:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-scheduling-service
spec:
  selector:
    app: appointment-scheduling
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
